# Generated by Django 4.1.6 on 2023-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='DINAMIK_PRODUCT',
            field=models.CharField(max_length=100, null=True, verbose_name='dinamic_products'),
        ),
        migrations.AddField(
            model_name='products',
            name='EKRAN_PRODUCT',
            field=models.CharField(max_length=100, null=True, verbose_name='ekran_products'),
        ),
        migrations.AddField(
            model_name='products',
            name='GODVIPUSKA_PRODUCT',
            field=models.CharField(max_length=100, null=True, verbose_name='godvipuska_products'),
        ),
        migrations.AddField(
            model_name='products',
            name='KAMERA_PRODUCT',
            field=models.CharField(max_length=100, null=True, verbose_name='kamera_products'),
        ),
    ]
